## A Support Vector Machine (SVM) is a supervised machine learning algorithm primarily used for classification tasks and in some cases regression too.<br><br>The main idea of SVM is to find the best line or boundary (called a hyperplane) that separates data into different classes.For 1D features,it draws line,for 2D it draws plane and for n dimesniona it draws hyperplane<br><br>SVM focuses on the most important and close data points, called support vectors, to create this boundary. These support vectors help define the hyperplane that best separates the classes and are close to the hyperplane.Hyperplane is drawn on the basis of support vector and small change in position of SV can cause hyperplane to be highly displaced<br><br>The hyperplane is drawn such that it has the wide margin from the closest point(support vector).Wide margin assures that even if data points moves a little bit from its original position,the line(hyperparameters) still correctly separates the groups.If hyperparameter have a narrow margin then If the dots move slightly, the line might no longer separate the groups correctly.

<img src = 'support-vector-machine-algorithm.png'/>

## In above,our dataset have two groups and a hyperplane(line) is drawn such that it separates the points of two group from the middle.The line drawn depends on the support vectors(nearest point to the line).Line is drawn acctoring to these SV.Small change in position of SV can cause line to displace its position

In [107]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
df = load_iris()

In [109]:
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [111]:
X = df['data']
Y = df['target']

In [113]:
X = pd.DataFrame(X,columns=['sepal_length','sepal_width','petal_length','petal_width'])
Y = pd.DataFrame(Y,columns=['targets'])

In [115]:
df.target_names ##It is provided in above load_iris data

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [142]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [125]:
flower = []
'''
for index,row in Y.iterrows():
    print(f'{index} {row}') ## Index will be giving index of a row and row will be giving value inside a row
    for value in row :
        if value == 0:
            flower.append('setosa')
        elif value == 1:
            flower.append('versicolor')
        elif value == 2 :
            flower.append('virginica')
flower = pd.DataFrame(flower)
'''

for val in Y.targets:
    if val == 0:
            flower.append('setosa')
    elif val == 1:
        flower.append('versicolor')
    elif val == 2 :
        flower.append('virginica')
flower = pd.DataFrame(flower)

In [127]:
flower.rename(columns={0:'flower'},inplace = True)

In [129]:
flower.sample(10)

         flower
10       setosa
46       setosa
97   versicolor
26       setosa
142   virginica
80   versicolor
29       setosa
63   versicolor
49       setosa
24       setosa

In [131]:
Y['flower'] = flower['flower']

In [135]:
Y

     targets     flower
0          0     setosa
1          0     setosa
2          0     setosa
3          0     setosa
4          0     setosa
..       ...        ...
145        2  virginica
146        2  virginica
147        2  virginica
148        2  virginica
149        2  virginica

[150 rows x 2 columns]

### Lets keep all this together and analyze this together

In [156]:
temp = np.hstack([X.columns,Y.columns])

In [162]:
dataframe = pd.concat([X,Y],axis = 1,ignore_index=True)

In [164]:
dataframe.columns = temp

In [166]:
dataframe

     sepal_length  sepal_width  petal_length  petal_width  targets     flower
0             5.1          3.5           1.4          0.2        0     setosa
1             4.9          3.0           1.4          0.2        0     setosa
2             4.7          3.2           1.3          0.2        0     setosa
3             4.6          3.1           1.5          0.2        0     setosa
4             5.0          3.6           1.4          0.2        0     setosa
..            ...          ...           ...          ...      ...        ...
145           6.7          3.0           5.2          2.3        2  virginica
146           6.3          2.5           5.0          1.9        2  virginica
147           6.5          3.0           5.2          2.0        2  virginica
148           6.2          3.4           5.4          2.3        2  virginica
149           5.9          3.0           5.1          1.8        2  virginica

[150 rows x 6 columns]

In [176]:
df1 = dataframe[dataframe.targets == 1] ## dataframe vanne dataframe ko targets column ko value 0 vayeko row ko whole row ko value select garera euta faltei dataframe return garcha

In [178]:
df1

    sepal_length  sepal_width  petal_length  petal_width  targets      flower
50           7.0          3.2           4.7          1.4        1  versicolor
51           6.4          3.2           4.5          1.5        1  versicolor
52           6.9          3.1           4.9          1.5        1  versicolor
53           5.5          2.3           4.0          1.3        1  versicolor
54           6.5          2.8           4.6          1.5        1  versicolor
55           5.7          2.8           4.5          1.3        1  versicolor
56           6.3          3.3           4.7          1.6        1  versicolor
57           4.9          2.4           3.3          1.0        1  versicolor
58           6.6          2.9           4.6          1.3        1  versicolor
59           5.2          2.7           3.9          1.4        1  versicolor
60           5.0          2.0           3.5          1.0        1  versicolor
61           5.9          3.0           4.2          1.5        1  versicolor
62           6.0          2.2           4.0          1.0        1  versicolor
63           6.1          2.9           4.7          1.4        1  versicolor
64           5.6          2.9           3.6          1.3        1  versicolor
65           6.7          3.1           4.4          1.4        1  versicolor
66           5.6          3.0           4.5          1.5        1  versicolor
67           5.8          2.7           4.1          1.0        1  versicolor
68           6.2          2.2           4.5          1.5        1  versicolor
69           5.6          2.5           3.9          1.1        1  versicolor
70           5.9          3.2           4.8          1.8        1  versicolor
71           6.1          2.8           4.0          1.3        1  versicolor
72           6.3          2.5           4.9          1.5        1  versicolor
73           6.1          2.8           4.7          1.2        1  versicolor
74           6.4          2.9           4.3          1.3        1  versicolor
75           6.6          3.0           4.4          1.4        1  versicolor
76           6.8          2.8           4.8          1.4        1  versicolor
77           6.7          3.0           5.0          1.7        1  versicolor
78           6.0          2.9           4.5          1.5        1  versicolor
79           5.7          2.6           3.5          1.0        1  versicolor
80           5.5          2.4           3.8          1.1        1  versicolor
81           5.5          2.4           3.7          1.0        1  versicolor
82           5.8          2.7           3.9          1.2        1  versicolor
83           6.0          2.7           5.1          1.6        1  versicolor
84           5.4          3.0           4.5          1.5        1  versicolor
85           6.0          3.4           4.5          1.6        1  versicolor
86           6.7          3.1           4.7          1.5        1  versicolor
87           6.3          2.3           4.4          1.3        1  versicolor
88           5.6          3.0           4.1          1.3        1  versicolor
89           5.5          2.5           4.0          1.3        1  versicolor
90           5.5          2.6           4.4          1.2        1  versicolor
91           6.1          3.0           4.6          1.4        1  versicolor
92           5.8          2.6           4.0          1.2        1  versicolor
93           5.0          2.3           3.3          1.0        1  versicolor
94           5.6          2.7           4.2          1.3        1  versicolor
95           5.7          3.0           4.2          1.2        1  versicolor
96           5.7          2.9           4.2          1.3        1  versicolor
97           6.2          2.9           4.3          1.3        1  versicolor
98           5.1          2.5           3.0          1.1        1  versicolor
99           5.7          2.8           4.1          1.3        1  versicolor